force-app/main/default/objects/RetryableJob__c/RetryableJob__c.object-meta.xml
<CustomObject>
    <label>RetryableJob</label>
    <nameField>
        <label>RetryableJob Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RetryableJobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RetryableJob__c/fields/className__c.field-meta.xml
<CustomField>
    <fullName>className__c</fullName>
    <label>className</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RetryableJob__c/fields/count__c.field-meta.xml
<CustomField>
    <fullName>count__c</fullName>
    <label>count</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RetryableJob__c/fields/firstTry__c.field-meta.xml
<CustomField>
    <fullName>firstTry__c</fullName>
    <label>First try</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/RetryableJob__c/fields/lastTry__c.field-meta.xml
<CustomField>
    <fullName>lastTry__c</fullName>
    <label>Last try</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/RetryableJob__c/fields/message__c.field-meta.xml
<CustomField>
    <fullName>message__c</fullName>
    <label>className</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RetryableJob__c/fields/nextTry__c.field-meta.xml
<CustomField>
    <fullName>nextTry__c</fullName>
    <label>Next try</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/RetryableJob__c/fields/serializedJob__c.field-meta.xml
<CustomField>
    <fullName>serializedJob__c</fullName>
    <label>parameters</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/RetryableJob__c/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <label>className</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BatchableRetry.cls
public with sharing class BatchableRetry implements Database.Batchable<SObject>, Database.AllowsCallouts {

    public Database.QueryLocator start(Database.BatchableContext context) {
        return Database.getQueryLocator([
                SELECT className__c, count__c, serializedJob__c, nextTry__c, firstTry__c
                FROM RetryableJob__c
                WHERE nextTry__c < :System.now()
                AND status__c = :Retryable.Status.FAILED_RETRY.name()
        ]);
    }

    public void execute(Database.BatchableContext context, List<SObject> jobs) {
        List<RetryableJob__c> jobsToUpdate = new List<RetryableJob__c>();
        for (Sobject job : jobs) {
            RetryableJob__c storedJob = (RetryableJob__c) job;
            Type jobType = Type.forName(storedJob.className__c);
            Retryable currentJob = (Retryable) JSON.deserialize(storedJob.serializedJob__c, jobType);
            JobResult jobResult = currentJob.retry();
            storedJob.status__c = jobResult.status.name();
            storedJob.nextTry__c = jobResult.status == Retryable.Status.FAILED_RETRY?  currentJob.getNextTry() : null;
            storedJob.lastTry__c = System.now();
            storedJob.serializedJob__c = JSON.serialize(currentJob);
            storedJob.count__c = storedJob.count__c + 1;
            storedJob.nextTry__c = currentJob.getNextTry();
            storedJob.message__c = jobResult.message;
            storedJob.status__c = jobResult.status.name();
            jobsToUpdate.add(storedJob);
        }
        update jobsToUpdate;
    }

    public void finish(Database.BatchableContext param1) {
        RetryScheduler.schedule();
    }

}