force-app/main/default/objects/RetryableJob__c/RetryableJob__c.object-meta.xml
<CustomObject>
    <label>RetryableJob</label>
    <nameField>
        <label>RetryableJob Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RetryableJobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RetryableJob__c/fields/className__c.field-meta.xml
<CustomField>
    <fullName>className__c</fullName>
    <label>className</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RetryableJob__c/fields/count__c.field-meta.xml
<CustomField>
    <fullName>count__c</fullName>
    <label>count</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RetryableJob__c/fields/firstTry__c.field-meta.xml
<CustomField>
    <fullName>firstTry__c</fullName>
    <label>First try</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/RetryableJob__c/fields/lastTry__c.field-meta.xml
<CustomField>
    <fullName>lastTry__c</fullName>
    <label>Last try</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/RetryableJob__c/fields/message__c.field-meta.xml
<CustomField>
    <fullName>message__c</fullName>
    <label>className</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RetryableJob__c/fields/nextTry__c.field-meta.xml
<CustomField>
    <fullName>nextTry__c</fullName>
    <label>Next try</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/RetryableJob__c/fields/serializedJob__c.field-meta.xml
<CustomField>
    <fullName>serializedJob__c</fullName>
    <label>parameters</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/RetryableJob__c/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <label>className</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Retryable.cls
public abstract class Retryable implements Queueable, Database.AllowsCallouts {

    public enum Status {
        MAX_RETRIES, FAILED_RETRY, SUCCEEDED, FAILED_ACTION_REQUIRED
    }
    protected List<Integer> retryScheduleInMinutes = new List<Integer>{
            1, 5, 10, 30, 60, 2 * 60, 4 * 60, 8 * 60, 16 * 60, 24 * 60
    };
    protected Datetime firstExecution;
    protected Integer retryCount = 0;
    private Datetime nextRetry;

    public void execute(QueueableContext context) {
        firstExecution = System.now();
        JobResult result = startJob();
        RetryScheduler.schedule();
        insertJob(result);
    }

    public JobResult retry() {
        retryCount++;
        nextRetry = isLastTry()
                ? null
                : firstExecution.addMinutes(retryScheduleInMinutes.get(retryCount));
        return isLastTry()
                ? JobResult.maximumRetries(startJob().message)
                : startJob();
    }

    protected abstract JobResult startJob();

    private void insertJob(JobResult result) {
        insert new RetryableJob__c(
                serializedJob__c = JSON.serialize(this),
                className__c = String.valueOf(this).split(':')[0],
                firstTry__c = System.now(),
                lastTry__c = System.now(),
                count__c = 1,
                nextTry__c = result.status == Retryable.Status.FAILED_RETRY
                        ? System.now().addMinutes(retryScheduleInMinutes.get(0))
                        : null,
                message__c = result.message,
                status__c = result.status.name()
        );
    }

    public Datetime getFirstExecution() {
        return firstExecution;
    }

    public Datetime getNextTry() {
        return nextRetry;
    }

    public Boolean isLastTry() {
        return retryCount >= retryScheduleInMinutes.size();
    }
}